// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppDateText: typeof import('./../components/app/DateText.vue')['default']
    AppDropdown: typeof import('./../components/app/Dropdown.vue')['default']
    AppEyeCatchImage: typeof import('./../components/app/EyeCatchImage.vue')['default']
    AppImage: typeof import('./../components/app/Image.vue')['default']
    AppSupplement: typeof import('./../components/app/Supplement.vue')['default']
    AppTagLabel: typeof import('./../components/app/TagLabel.vue')['default']
    DbeArticle: typeof import('./../components/dbe/Article.vue')['default']
    DbeLayoutFooter: typeof import('./../components/dbe/layout/Footer.vue')['default']
    DbeLayoutHeader: typeof import('./../components/dbe/layout/Header.vue')['default']
    DbeLayoutLogo: typeof import('./../components/dbe/layout/Logo.vue')['default']
    DbeLinkCard: typeof import('./../components/dbe/LinkCard.vue')['default']
    DbePagenation: typeof import('./../components/dbe/Pagenation.vue')['default']
    DbeShareButtons: typeof import('./../components/dbe/ShareButtons.vue')['default']
    DbeShareButtonsMenu: typeof import('./../components/dbe/ShareButtonsMenu.vue')['default']
    DbeShopItemCard: typeof import('./../components/dbe/ShopItemCard.vue')['default']
    DbeSideDropdown: typeof import('./../components/dbe/side/Dropdown.vue')['default']
    DbeSideProfile: typeof import('./../components/dbe/side/Profile.vue')['default']
    DbeSideText: typeof import('./../components/dbe/side/Text.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
