// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppDateText: typeof import('./../components/app/DateText.vue')['default']
    AppDropdown: typeof import('./../components/app/Dropdown.vue')['default']
    AppEyeCatchImage: typeof import('./../components/app/EyeCatchImage.vue')['default']
    AppImage: typeof import('./../components/app/Image.vue')['default']
    AppSupplement: typeof import('./../components/app/Supplement.vue')['default']
    AppTagLabel: typeof import('./../components/app/TagLabel.vue')['default']
    AppText: typeof import('./../components/app/Text.vue')['default']
    BaArticle: typeof import('./../components/ba/Article.vue')['default']
    BaLayoutFooter: typeof import('./../components/ba/layout/Footer.vue')['default']
    BaLayoutHeader: typeof import('./../components/ba/layout/Header.vue')['default']
    BaLinkCard: typeof import('./../components/ba/LinkCard.vue')['default']
    BaLogo: typeof import('./../components/ba/Logo.vue')['default']
    BaPagenation: typeof import('./../components/ba/Pagenation.vue')['default']
    BaShareButtons: typeof import('./../components/ba/ShareButtons.vue')['default']
    BaShareButtonsMenu: typeof import('./../components/ba/ShareButtonsMenu.vue')['default']
    BaShopItemCard: typeof import('./../components/ba/ShopItemCard.vue')['default']
    BaSideDropdown: typeof import('./../components/ba/side/Dropdown.vue')['default']
    BaSideProfile: typeof import('./../components/ba/side/Profile.vue')['default']
    BaSideText: typeof import('./../components/ba/side/Text.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
